Profile
BonApp12/BonApp pull request #43
Opened 2022-05-30 14:31 UTC by Djaizansi

* Ajoute le design de l'utilisateur lorsqu'il est connecté
* Ajoute le système de modification du profile
* Ajoute l'affichage des dernières commandes effectuées

2022-06-06 18:36 UTC, yassansplus requested changes
La daronne a wassim en quad LETS GOOOOO

![image](https://user-images.githubusercontent.com/34783077/172224498-9ee6e6d4-413c-4a90-b215-e0b17bff5fe0.png)

2022-06-06 18:36 UTC, yassansplus commented on packages/frontend/src/components/Disconnect/Disconnect.js
> +            setUserState(undefined);
Il est préférable d'éviter undefined, plutot utiliser null voilà ici pourquoi : [LIEN](https://stackoverflow.com/questions/6604749/what-reason-is-there-to-use-null-instead-of-undefined-in-javascript#:~:text=Only%20use%20null%20if%20you,defined%20reference%20to%20%22nothing%22.)

2022-06-06 18:36 UTC, yassansplus commented on packages/frontend/src/components/Input/Input.js
> +export default function Input({type,name,register,placeHolder,error=null,label=null, disabled=false}){
c'est un objet, comment ça se fait que le "=" fonctionne à l'interieur ? normalement on utilise des points

2022-06-06 18:36 UTC, yassansplus commented on packages/frontend/src/components/ProductDetail/ProductDetail.js
> +    else if (!isLoaded) return <div><LoadingPage color={"gray"}/></div>;
juste if sans le else

2022-06-06 18:36 UTC, yassansplus commented on packages/frontend/src/components/Profile/OrdersAccount.js
> +    const [filter, setFilter] = useState([]);
c'est un tableau c'est filters

2022-06-06 18:36 UTC, yassansplus commented on packages/frontend/src/components/Profile/OrdersAccount.js
> +    const activeBtn = (event,type) => {
à quoi fait référence type, essaye de donner un nom plus explicite

2022-06-06 18:36 UTC, yassansplus commented on packages/frontend/src/components/Profile/OrdersAccount.js
> +    const [filter, setFilter] = useState([]);
ça te permet de filtrer les Order? si Oui donne aussi un nom plus pragmatique

2022-06-06 18:36 UTC, yassansplus commented on packages/frontend/src/components/Profile/SettingsAccount.js
> +        });
ça sert à quoi ça ?

2022-06-06 18:36 UTC, yassansplus commented on packages/frontend/src/components/Profile/SettingsAccount.js
> +                        ['oldPassword','password','confirmPassword'].forEach(field => setValue(field,''));
j'ai l'impression que ces variables tu t'en sers à 2 endroits c'est pas possible de mutualisé ça?

2022-06-06 18:36 UTC, yassansplus commented on packages/frontend/src/fields/profileFields.js
> +const profileFields = {
même carrément récupérer cette objet et bosser dessus

2022-06-12 16:12 UTC, 12Wass commented
> La daronne a wassim en quad LETS GOOOOO
> 
> ![image](https://user-images.githubusercontent.com/34783077/172224498-9ee6e6d4-413c-4a90-b215-e0b17bff5fe0.png)

Petit salaud tu croyais que j'allais pas lire ?

2022-06-12 16:13 UTC, Djaizansi commented
> > La daronne a wassim en quad LETS GOOOOO
> > ![image](https://user-images.githubusercontent.com/34783077/172224498-9ee6e6d4-413c-4a90-b215-e0b17bff5fe0.png)
> 
> Petit salaud tu croyais que j'allais pas lire ?

Ca va se tape ici et maintenant en commentaire

2022-06-12 16:13 UTC, yassansplus commented
HAHAHAHAHAHAHAHAHAAHAHAH

2022-06-12 16:13 UTC, yassansplus approved these changes

2022-06-12 16:15 UTC, merged

2022-06-13 08:41 UTC, 12Wass commented
@yassansplus @Djaizansi je crois que le merge de ce ticket à FUMER quelques trucs, notamment au niveau des Adapters

2022-06-13 08:43 UTC, Djaizansi commented
> @yassansplus @Djaizansi je crois que le merge de ce ticket à FUMER quelques trucs, notamment au niveau des Adapters

Moi j'ai pas eu de problème, j'ai tout supprimé avec un prune au niveau des volumes et du systeme carrement.

2022-06-13 08:44 UTC, yassansplus commented
Wass go discord si tu veux