Génération de PDF
BonApp12/BonApp pull request #56
Opened 2022-06-28 23:02 UTC by Djaizansi

* Ajoute la génération de PDF.
* Ajoute une entité permettant la jointure entre une commande et un plat afin d'obtenir plusieurs plats en fonction d'une commande.

2022-06-29 14:40 UTC, yassansplus requested changes

2022-06-29 14:40 UTC, yassansplus commented on packages/backend/src/Adapter/PlateAdapter.ts
> +        // plateDto.orders = plate?.orders;
à supprimer

2022-06-29 14:40 UTC, yassansplus commented on packages/backend/src/Adapter/PlateAdapter.ts
> +        // plateDto.orders = JSON.parse(plate?.orders || '[{}]');
à supprimer

2022-06-29 14:40 UTC, yassansplus commented on packages/backend/src/Adapter/PlateAdapter.ts
> +        // plateModel.orders = plate?.orders;
à supprimer

2022-06-29 14:40 UTC, yassansplus commented on packages/backend/src/Adapter/PlateAdapter.ts
> +        // plateModel.orders = plate?.orders;
à supprimer

2022-06-29 14:40 UTC, yassansplus commented on packages/backend/src/main.ts
> +    origin: ['http://localhost:3000', "http://localhost:3001", "http://localhost:8888","http://localhost:8081","http://localhost:8080"], // TODO : Rajouter le domaine de production.
ajoute une TODO : à mutualiser dans le .env

2022-06-29 14:40 UTC, yassansplus commented on packages/backend/src/order-plate/dto/create-order-plate.dto.ts
> +export class CreateOrderPlateDto {}
Fichier à supprimer

2022-06-29 14:40 UTC, yassansplus commented on packages/backend/src/order-plate/dto/update-order-plate.dto.ts
> +export class UpdateOrderPlateDto extends PartialType(CreateOrderPlateDto) {}
pareille

2022-06-29 14:40 UTC, yassansplus commented on packages/backend/src/order-plate/order-plate.service.ts
> +  }
il manque pas le commentaire qu'on a fait hier ensemble, genre comment on créé un order?

2022-06-29 14:40 UTC, yassansplus commented on packages/backend/src/order-plate/order-plate.service.ts
> +  }
ah bah non c'est pas ici mais le create ici, il est sensé être rempli s'il ne fait rien pour l'heure supprime les méthode qiu ne serve rien

2022-06-29 14:40 UTC, yassansplus commented on packages/backend/src/pdf/order.variable.ts
> +}
ce fichier sert à quoi, il ressemble à un adapter un peu?

2022-06-29 14:40 UTC, yassansplus commented on packages/frontend/src/components/Profile/OrdersAccount.js
> +                                                <button className="btn text-white bg-orange-500 border-orange-500 gap-x-2 mt-4" onClick={() => generatePdf(order.id)}><span className="text-white"><AiO
indent stp

2022-06-29 14:40 UTC, yassansplus commented on packages/frontend/src/components/Profile/OrdersAccount.js
> +                                <p>{plate.plate.name} <b>x{plate.quantity}</b> - <b>{plate.price * plate.quantity} €</b></p>
au lieu des <b> fait un span avec bold en tailwind

2022-06-29 14:40 UTC, yassansplus commented on packages/frontend/src/components/Profile/OrdersAccount.js
> +                                <img src={plate.plate.type === "ENTREE" ? starter : (plate.plate.type === 'PLAT' ? dish : dessert)} alt="starter" className="w-8 h-8 inline-block"/>
Tu as un Enum pour ENTREE PLAT

2022-06-29 21:11 UTC, Djaizansi commented on packages/backend/src/pdf/order.variable.ts
> +}
Ce fichier permet en gros mettre en forme ce dont j'ai besoin. Fullname et tout le reste n'existe pas en base. J'ai fait exprès parce que dans mon fichier html, j'ai mis en place ces noms de valeurs. J'ai donc créer ce fichier afin de boucler sur mon objet et ne pas faire plusieurs fois la même "ligne" du style : "html.replace()". La je boucle donc j'ai juste une seule ligne. Un Adapter c'est différent a moins que je le renomme comme ca mais cet objet est uniquement pour mon pdf c'est tout.

2022-06-30 00:05 UTC, yassansplus approved these changes

2022-06-30 19:24 UTC, merged